added the result for Sonar

diff --git a/.github/workflows/devsecops.yaml b/.github/workflows/devsecops.yaml
--- a/.github/workflows/devsecops.yaml
+++ b/.github/workflows/devsecops.yaml
@@ -54,4 +54,26 @@ jobs:
             -Dsonar.sourceEncoding=UTF-8 \
             -Dsonar.host.url=$SONAR_HOST_URL \
             -Dsonar.login=$SONAR_TOKEN
-
+       
+      - name: Wait for SonarQube Quality Gate Result
+        env:
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          echo "⏳ Checking Quality Gate status..."
+          for i in {1..20}; do
+            status=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=eks-3tier-app" | jq -r '.projectStatus.status')
+            echo "Current status: $status"
+            if [ "$status" == "OK" ]; then
+              echo "✅ Quality Gate PASSED!"
+              exit 0
+            elif [ "$status" == "ERROR" ]; then
+              echo "❌ Quality Gate FAILED!"
+              exit 1
+            else
+              echo "⏳ Waiting for analysis to finish..."
+              sleep 15
+            fi
+          done
+          echo "⚠️ Timed out waiting for Quality Gate result."
+          exit 1
